version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u $dockerhub_username -p $dockerhub_password
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 250907706023.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg AWS_ACCESS_KEY_ID=$aws_access_key --build-arg AWS_SECRET_ACCESS_KEY=$aws_secret_access_key -t staging-pyentry .
      - docker tag staging-pyentry:latest 250907706023.dkr.ecr.eu-west-1.amazonaws.com/staging-pyentry:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 250907706023.dkr.ecr.eu-west-1.amazonaws.com/staging-pyentry:latest
      - printf '[{"name":"staging-pyentry","imageUri":"%s"}]' 250907706023.dkr.ecr.eu-west-1.amazonaws.com/staging-pyentry:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
