FROM ubuntu:22.04

# Newrelic
ENV NEW_RELIC_LICENSE_KEY eu01xxaa9ee707eaca448663b849baf3FFFFNRAL
ENV NEW_RELIC_APP_NAME "Staging-Py-Entry-Celery"
ENV NEW_RELIC_CONFIG_FILE newrelic.ini

# Install pkg-config
RUN apt-get -y update && apt-get install -y python3 python3-pip wget \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config unzip
    

# Install AWS CLI
# RUN apt-get install -y unzip wget
RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" && \
    unzip awscli-exe-linux-x86_64.zip && \
    ./aws/install
    
#  Copy AWS access credentials
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY    

# Download file from S3
RUN aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} && \
    aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} && \
    aws s3 cp s3://wescoop-devops-config-private/STAGING/STAGING-PYENTRY/.env /app/  && \
    aws s3 cp s3://wescoop-devops-config-private/STAGING/STAGING-PYENTRY/newrelic.ini /app/

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip3 install Flask
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

EXPOSE 5000

# CMD ["celery", "-A", "celery_worker.celery", "worker", "--loglevel=info"]
# CMD ["newrelic-admin", "run-program", "celery", "-A", "celery_worker.celery", "worker", "--loglevel=info", "-c", "4", "-P", "prefork"]

# Commneted for stop sending logs in Newrelic
# CMD ["newrelic-admin", "run-program", "celery", "-A", "celery_worker.celery", "worker", "--loglevel=info", "-c", "4", "-P", "prefork"]
CMD ["celery", "-A", "celery_worker.celery", "worker", "--loglevel=info", "-c", "4", "-P", "prefork"]